GET http://localhost:3333/users HTTP/1.1
Content-Type: application/json

###
POST http://localhost:3333/users HTTP/1.1
Content-Type: application/json

{
    "name": "Lucas",
    "email": "lucas@email.com",
    "password": "1234"
}

###
GET http://localhost:3333/clients HTTP/1.1
Content-Type: application/json

###
POST http://localhost:3333/clients HTTP/1.1
Content-Type: application/json

{
    "name": "Lucas", 
    "cpf": "01234567890",
    "phone": "16999999999",
    "email": "johndoe@email.com",
    "address": "Rua dos bobos",
    "number": "0",
    "neighborhood": "Jd. da Luz",
    "complement": "",
    "zipCode": "13555555"
}

###
GET http://localhost:3333/clients/1 HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3333/payments/method HTTP/1.1
Content-Type: application/json

###
POST http://localhost:3333/payments/method HTTP/1.1
Content-Type: application/json

{
    "id": "debit",
    "name": "Débito"
}

###

GET http://localhost:3333/payments/client/2 HTTP/1.1
Content-Type: application/json

###

POST http://localhost:3333/payments/client/1 HTTP/1.1
Content-Type: application/json

{
    "amount": 100,
    "paymentMethod": "credit",
    "due": "2024-06-05"
}

###

POST http://localhost:3333/plan HTTP/1.1
Content-Type: application/json

{
    "name": "Mensal",
    "description": "Neste a pessoa tem acesso total a acadêmia durante a horario de funcionamnto",
    "price": 1000,
    "recurrency": "MONTH"
}

###

GET http://localhost:3333/plans HTTP/1.1
Content-Type: application/json

###

GET http://localhost:3333/plan/1 HTTP/1.1
Content-Type: application/json

###

POST http://localhost:3333/subscription/client/1/plan/1 HTTP/1.1

###

GET http://localhost:3333/subscriptions HTTP/1.1
Content-Type: application/json

###

GET http://localhost:3333/subscriptions/client/2 HTTP/1.1
Content-Type: application/json
